# Set array
$azPolicy = @()
#Get Subscription.
#If you want to run through all subscriptions that you have access for,
#then don't give subscriptionID as shown below commented line
#$azSubs = Get-AzSubscription
$azSubs = Get-AzSubscription -SubscriptionId c1846e32-d865-470b-86fa-daee66cd7830
# Loop through all Azure Subscriptions
foreach ($azSub in $azSubs) {
Set-AzContext $azSub.id | Out-Null
$nonCompliantResources = Get-AzPolicyState -PolicyAssignmentName $(AzPolicyAssignmentName) -Filter "ComplianceState eq 'NonCompliant'"
$nonCompliantResources | Select-Object resourcegroup, @{N='ResourceName';E={$_.resourceId.Split('/')[-1]}},resourcetype,compliancestate,resourcelocation | Export-Csv .\$(AzSubscriptionID).csv -NoTypeInformation
}